server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost/task-tracker
    username: postgres
    password: core76
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update